# Generated by Django 4.0.3 on 2022-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_normal', models.URLField(unique=True, verbose_name='URL')),
                ('url_encurtada', models.CharField(max_length=20, null=True, unique=True, verbose_name='URL Menor')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateField(blank=True, verbose_name='Data de Expiração')),
            ],
        ),
    ]
