# Generated by Django 4.0.3 on 2022-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_urls_url_encurtada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
    ]
