# Generated by Django 4.0.3 on 2022-03-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_urls_data_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='ativo',
        ),
    ]
